output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.region
}

output "node_groups" {
  description = "Outputs from node groups"
  value       = module.eks.node_groups
}

output "dns_zone" {
  value     = aws_route53_zone.zeet.zone_id
}

output "aws_account_id" {
  value = data.aws_caller_identity.current.account_id
}

output "cluster_id" {
  value = var.cluster_id
}

output "cluster_name" {
  value = var.cluster_name
}

output "ssh_public" {
  value     = tls_private_key.ssh.public_key_openssh
}

output "ssh_private" {
  sensitive = true
  value     = tls_private_key.ssh.private_key_pem
}
